add-header/add-modal
InnaIvBoiko/Kryptonite-Breakers pull request #2
Opened 2023-11-25 22:43 UTC by olhadibrova

2023-11-25 23:28 UTC, InnaIvBoiko requested changes

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +    <header class="header">
Видали все до п.10 починаєш із тегу header

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                    <img src="./img/logo/logo.svg" alt="Site logotype" width="44" height="40" class="header-logo-img" />
тут вроді 39 висота

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                <address class="header-contacts">
кнопка не потрібна, просто
<address class="header-contacts">
          <a class="header-phone-link" href="tel:+380684439426">+380 (68) 443-94-26</a>
</address>

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                            <svg class="header-social-svg" width="40" height="40">
width: 28px;
height: 28px;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +            <div class="header-social-container">
замість контейнер я б використала wrap

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                            <svg class="header-social-svg" width="40" height="40">
width: 28px;
height: 28px;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                            <svg class="header-social-svg" width="40" height="40">
width: 28px;
height: 28px;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                    <svg width="" height="" class="header-icon-burger-menu">
width="36" height="24"

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                    <button type="button" class="header-mobile-phone-btn">
видаляєм button

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +                    <svg width="" height="" class="header-mobile-icon">
width: 36px;
height: 36px;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/partials/header.html
> +</body>
видаляємо все після </header>

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/css/header.css
> +    background: rgba(252, 249, 249, 0.10);
+ opacity: 0.8;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/css/header.css
> +.header-social-item {
тут пропоную додати.     padding: 4px 0;

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/css/header.css
> +.is-open {
є вже прописано в базових властивостях, якщо не працює без цього коду - залишайте, потім почистю базовий

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/css/header.css
> + background-image: url(../img/bg-elements/bg-el-menu-mob.png);
тут я б зробила пустий дів в html файлі і йому задала б властивість background-image: url(..
і памʼятайте про крапки на початку шляху

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/css/header.css
> + background-image: url(../img/bg-elements/bg-el-menu-mob.png);
подивіться order як зразок

2023-11-25 23:28 UTC, InnaIvBoiko commented on src/img/bg-elements/bg-el-menu-mob@2x.png
вам дійсно потрібно змінювати ці файли? вони однакові

2023-11-26 11:41 UTC, olhadibrova commented on src/img/bg-elements/bg-el-menu-mob@2x.png
Коли вирішувала проблему з розміром @2х зображення, перевіряла чи валідні зображення. Можно не змінювати вони були в нормі.

2023-11-26 11:41 UTC, olhadibrova commented on src/css/header.css
> +.is-open {
Без нього не працює. Залишила.

2023-11-26 12:56 UTC, InnaIvBoiko requested changes

2023-11-26 12:56 UTC, InnaIvBoiko commented on src/css/header.css
> +.header-burger-btn {
padding: 0;
    line-height: 0;

2023-11-26 12:56 UTC, InnaIvBoiko commented on src/css/header.css
> +   padding-right: 8px;
Може краще поміняти gap: 20px; в .header-social-wrap

2023-11-26 12:56 UTC, InnaIvBoiko commented on src/css/header.css
> +   padding-right: 8px;
Цей падінг тобі тянеться на десктоп

2023-11-26 12:56 UTC, InnaIvBoiko commented on src/partials/header.html
> +        <div class="header-mobile-menu ">
тут потрібно додати дів модальне вікно для затемнення екрану. йому фіксовану позицію, а до нього вже абсолютом мобільне меню
.modal-menu {
  position: fixed;
  top: 0;
  left: 0;
  z-index: 99999;
  width: 100%;
  height: 100%;
  background-color: rgba(252, 249, 249, 0.1);

  /* for not visibily */
  opacity: 0;
  visibility: hidden;
  pointer-events: none;
  transition: opasity, visibility 250ms linear;
}

.modal-menu.is-open {
  opacity: 1;
  visibility: visible;
  pointer-events: auto;
}

.header-mobile-menu{
  position: absolute;
  top: 0;
  right: 0;
  .......
}

2023-11-26 15:20 UTC, InnaIvBoiko requested changes
Тут ще висять твої bg-elements, що з ними робитимемо?  Вони оптимізовані?

2023-11-26 15:20 UTC, InnaIvBoiko commented on src/css/header.css
> +   .header-social-list {
Тут пусто, треба видалити

2023-11-26 15:20 UTC, InnaIvBoiko commented on src/css/header.css
> + overflow: auto;
це тут не потрібне, тільки в backdrop

2023-11-26 17:43 UTC, InnaIvBoiko requested changes

2023-11-26 17:43 UTC, InnaIvBoiko commented on src/css/header.css
не підтягує коректно @1x @2x  
тут потрібно виправити
@media (-webkit-min-device-pixel-ratio: 2),
   (min-resolution: 192dpi),
   (min-resolution: 2dppx) {
    .header-mobile-menu {
    background-image:
     url(../img/bg-elements/bg-el-menu-tab@2x.png);
    background-repeat: no-repeat;
    background-position: bottom;
    background-size: contain;
    }
   }

Спробуй

@media screen and (min-resolution: 192dpi) and (max-width: 767px),
  screen and (min-resolution: 2dppx) and (max-width: 767px),
  screen and (min-device-pixel-ratio: 2) and (max-width: 767px) {
  .header-mobile-bg-el {
    background-image:    url(./img/bg-elements/bg-el-menu-mob@2x.png);
}

і для таблета спочатку міняєш в @media .... url() і памʼятай що потрібно видалити 1 крапку для всіх зображень, а потім додай правила зміни ретіни екрану

@media screen and (min-resolution: 192dpi) and (min-width: 768px),
  screen and (min-resolution: 2dppx) and (min-width: 768px),
  screen and (min-device-pixel-ratio: 2) and (min-width: 768px) {
  .header-mobile-bg-el {
    background-image:    url(./img/bg-elements/bg-el-menu-tab@2x.png);
}

2023-11-26 20:58 UTC, InnaIvBoiko approved these changes

2023-11-26 20:58 UTC, merged